"""
Convert a Google Cloud service-account JSON file + a Sheet key into a
ready-to-use .streamlit/secrets.toml.

Usage:
    python setup_sheets.py path/to/service-account.json \
        --sheet-key 1AbCdEfGhIjKlMnOpQrStUvWxYz1234567890 \
        [--worksheet Submissions]

The script then connects to the sheet and writes a 'hello' row to confirm
everything works end-to-end. If anything fails, it prints a clear error
explaining what to fix.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def _emit_toml(sa: dict, sheet_key: str, worksheet: str) -> str:
    """Render service-account dict + sheet info as TOML."""
    lines: list[str] = []
    lines.append("# Generated by setup_sheets.py — DO NOT COMMIT THIS FILE.")
    lines.append("")
    lines.append("[sheet]")
    lines.append(f'key = "{sheet_key}"')
    lines.append(f'worksheet = "{worksheet}"')
    lines.append("")
    lines.append("[gcp_service_account]")
    for k in (
        "type", "project_id", "private_key_id", "private_key",
        "client_email", "client_id", "auth_uri", "token_uri",
        "auth_provider_x509_cert_url", "client_x509_cert_url",
        "universe_domain",
    ):
        if k not in sa:
            continue
        v = sa[k]
        if k == "private_key":
            # TOML literal-string would be cleanest, but Streamlit's secrets
            # parser handles regular strings with embedded \n just fine.
            v_escaped = v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            lines.append(f'{k} = "{v_escaped}"')
        else:
            v_escaped = str(v).replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{k} = "{v_escaped}"')
    lines.append("")
    return "\n".join(lines)


def _smoke_test(secrets_path: Path, sheet_key: str, worksheet: str) -> None:
    """Connect to the sheet and append a 'hello' row to verify the setup."""
    try:
        import gspread
        from google.oauth2.service_account import Credentials
    except ImportError as e:
        print(f"[!] Missing dependency: {e}. Run: pip install -r requirements.txt")
        sys.exit(1)

    sa = json.loads(Path(secrets_path.parent / "_sa_temp.json").read_text())
    creds = Credentials.from_service_account_info(
        sa,
        scopes=[
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/drive",
        ],
    )
    client = gspread.authorize(creds)
    try:
        spreadsheet = client.open_by_key(sheet_key)
    except Exception as exc:
        print()
        print("[!] Could not open the sheet. Common causes:")
        print(f"    - You forgot to share the sheet with {sa['client_email']!r}")
        print("      (give it 'Editor' access).")
        print("    - The --sheet-key value is wrong. It should be the long")
        print("      string between /d/ and /edit in your sheet's URL.")
        print(f"    - Original error: {exc}")
        sys.exit(1)

    try:
        ws = spreadsheet.worksheet(worksheet)
    except gspread.WorksheetNotFound:
        ws = spreadsheet.add_worksheet(title=worksheet, rows=1000, cols=26)
        ws.append_row(["timestamp_utc", "event", "note"])

    ws.append_row([
        datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "setup-smoke-test",
        "Setup OK — you can delete this row.",
    ])
    print(f"[OK] Wrote a smoke-test row to '{worksheet}' in your sheet.")
    print(f"     Open: https://docs.google.com/spreadsheets/d/{sheet_key}/")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("service_account_json", help="Path to the JSON key file you "
                                                "downloaded from Google Cloud.")
    p.add_argument("--sheet-key", required=True,
                   help="The long string between /d/ and /edit in your sheet URL.")
    p.add_argument("--worksheet", default="Submissions",
                   help="Tab name inside the sheet (default: Submissions).")
    args = p.parse_args()

    sa_path = Path(args.service_account_json).expanduser()
    if not sa_path.exists():
        print(f"[!] {sa_path} not found.")
        sys.exit(1)

    try:
        sa = json.loads(sa_path.read_text())
    except json.JSONDecodeError as e:
        print(f"[!] {sa_path} is not valid JSON: {e}")
        sys.exit(1)

    for required in ("client_email", "private_key", "project_id"):
        if required not in sa:
            print(f"[!] JSON is missing required field {required!r}. "
                  "Did you download the *service account* key (not OAuth client)?")
            sys.exit(1)

    here = Path(__file__).parent
    streamlit_dir = here / ".streamlit"
    streamlit_dir.mkdir(exist_ok=True)
    secrets_path = streamlit_dir / "secrets.toml"

    if secrets_path.exists():
        print(f"[i] {secrets_path} already exists. Backing up to "
              f"{secrets_path.name}.bak")
        secrets_path.rename(secrets_path.with_suffix(".toml.bak"))

    toml_text = _emit_toml(sa, args.sheet_key, args.worksheet)
    secrets_path.write_text(toml_text)
    print(f"[OK] Wrote {secrets_path}")

    # Smoke-test the connection
    (streamlit_dir / "_sa_temp.json").write_text(json.dumps(sa))
    try:
        _smoke_test(secrets_path, args.sheet_key, args.worksheet)
    finally:
        (streamlit_dir / "_sa_temp.json").unlink(missing_ok=True)

    print()
    print("Next step: stop the running Streamlit (Ctrl+C in its terminal) and "
          "run it again so it loads the new secrets:")
    print("    streamlit run app.py")
    print()
    print("After it boots, your next submission should land in the sheet "
          "instead of submissions/*.json.")


if __name__ == "__main__":
    main()
